### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by PowerPress** [vonahi-security/leprechaun#1]
Can you please provide a link to Josh Stone's routehunter since I have been unable to find it anywhere. Thanks

**Comment by altjx** [comment]
@PowerPress absolutely. Waiting on the author to update and upload his code and will make it available. If you're needing it sooner, one of the commands I've used frequently is: `for i in $(cat /systems/with/445/open.txt); do winexe //$i -U domain/user%password "netstat -an"; done | tee netstat_results.txt`

Hope this helps as a temporary workaround until his code is uploaded.

Thanks!

**Comment by altjx** [comment]
Hi @PowerPress ,

Unfortunately the author is not releasing the tool to the public. However, in general, the script runs a recursive `netstat -an | findstr -i established` on all accessible systems and then outputs that into text files.

If you need any assistance with creating a small script to do this, let me know. I will close this issue out for now.

**Comment by PowerPress** [comment]
If you dont mind creating the script that would be great with leprechaun
