### ISSUE TITLE
Lowercase TCP is printed as UDP in output.

### ISSUE THREAD

**Issue by duncrow** [vonahi-security/leprechaun#2]
**Lowercase (incorrect):**
$ cat lowercase.txt ; ./leprechaun.rb -f lowercase.txt -p all
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
**tcp**        0      0 1.2.3.4:52796       5.6.7.8:22       ESTABLISHED

 [*] Completed! Graph output file located at: ./network_diagram.png

+---------+-----------------------------+----------------------------------+
| Server  | Number of connected clients | Highest traffic destination port |
+---------+-----------------------------+----------------------------------+
| 5.6.7.8 | 1                           | **22/udp** (1 connections)           |
+---------+-----------------------------+----------------------------------+

**Uppercase (correct):**
$ cat uppercase.txt ; ./leprechaun.rb -f uppercase.txt -p all
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
**TCP**        0      0 1.2.3.4:52796       5.6.7.8:22       ESTABLISHED

 [*] Completed! Graph output file located at: ./network_diagram.png

+---------+-----------------------------+----------------------------------+
| Server  | Number of connected clients | Highest traffic destination port |
+---------+-----------------------------+----------------------------------+
| 5.6.7.8 | 1                           | **22/tcp** (1 connections)           |
+---------+-----------------------------+----------------------------------+

**Comment by altjx** [comment]
Fixed. Thanks @duncrow!
