### ISSUE TITLE
ERROR:  Could not find a valid gem 'securerandom' (>= 0) in any repository

### ISSUE THREAD

**Issue by junmoxiao** [vonahi-security/leprechaun#3]
gem install 'securerandom'
ERROR:  Could not find a valid gem 'securerandom' (>= 0) in any repository

**Comment by altjx** [comment]
Hi @junmoxiao,

That's strange. Do you get `true` when running the following command?

```
# irb
irb(main):001:0> require 'securerandom'
=> true
irb(main):002:0> exit
```

**Comment by junmoxiao** [comment]
I installed "secure_random_string" and "securer_randomer" and then can run it.
But no graph generate.

After read the code
`sfdp -Tpng data.dot -o leprechaun_#{tmp_file}.png -Grankdir=LR; rm data.dot`

The tool also need graphviz, Installed it and all things right.

Thank you .

**Comment by altjx** [comment]
@junmoxiao ,

Perfect. Thanks! Glad it worked! Let me know if you have any further issues.

**Comment by The-legend3** [comment]
Having the same issue. Installed "secure_random_string", "securer_randomer",  "rubysl-securerandom" and still no output.
