### ISSUE TITLE
uninitialized constant IPAddr (NameError)

### ISSUE THREAD

**Issue by nothing-fr** [vonahi-security/leprechaun#4]
Hi,

When launching leprechaun, I have this error :

```
❯ ./leprechaun.rb
Traceback (most recent call last):
./leprechaun.rb:32:in `<main>': uninitialized constant IPAddr (NameError)
```
I don't understand why, do I have to modify or install something else to make it work ?

Regards,

**Comment by nothing-fr** [comment]
I've commented this block : 

```
#PRIVATE_IPS = [
#       IPAddr.new('10.0.0.0/8'),
#       IPAddr.new('172.16.0.0/12'),
#       IPAddr.new('192.168.0.0/16'),
#].freeze
```

and it seems to be working now...

**Comment by altjx** [comment]
Hi @nothing-fr ,

Thanks for bringing this to our attention. It looks like there was a dependency that was not being required when starting the script. I've added that into the script and you should be all set now.

Let me know if you run into any other issues. Thanks again for reporting this.

Happy Friday and have a great weekend!
